# Generated by Django 4.2.3 on 2023-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_author_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='subheadings',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
