# Generated by Django 4.2.3 on 2023-08-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subheadings',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
