# Generated by Django 4.2.3 on 2023-08-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_remove_post_conclusion_remove_post_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='subheadings',
            field=models.TextField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
