# Generated by Django 4.2.3 on 2023-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_author_alter_post_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Author', max_length=100),
        ),
    ]
